# Default values for finops-k8s-operator.
# Users can override these when installing or upgrading the chart.

image:
  repository: ghcr.io/ok-karthik/finops-k8s-operator
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

annotations: {}

scheduleInterval: 60
