apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finops-k8s-operator.fullname" . }}
  labels:
    app: {{ include "finops-k8s-operator.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "finops-k8s-operator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "finops-k8s-operator.name" . }}
    spec:
      serviceAccountName: {{ include "finops-k8s-operator.fullname" . }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kopf", "run", "operator.py"]
          # mount config or secrets if necessary
