{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-k8s-operator.fullname" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end -}}
